[project]
name = "PyBash"
version = "0.1.0"
description = "Simple Bash-like Python shell"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "typer>=0.20.0",
]
